---
cidr_networks:
  container_cab1: 172.16.1.0/24
  container_cab2: 172.16.2.0/24
  container_cab3: 172.16.3.0/24
  tunnel_cab1: 172.17.1.0/24
  tunnel_cab2: 172.17.2.0/24
  tunnel_cab3: 172.17.3.0/24
  storage_cab1: 172.18.1.0/24
  storage_cab2: 172.18.2.0/24
  storage_cab3: 172.18.3.0/24

used_ips:
  - "172.16.1.1,172.16.1.50"
  - "172.16.2.1,172.16.2.50"
  - "172.16.3.1,172.16.3.50"
  - "172.17.1.1,172.17.1.50"
  - "172.17.2.1,172.17.2.50"
  - "172.17.3.1,172.17.3.50"
  - "172.18.1.1,172.18.1.50"
  - "172.18.2.1,172.18.2.50"
  - "172.18.3.1,172.18.3.50"

global_overrides:
  internal_lb_vip_address: 172.16.1.1
  external_lb_vip_address: 10.127.83.31
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container_cab1"
        type: "raw"
        group_binds:
          - cab1-containers
          - cab1-hosts
        is_container_address: true
        is_ssh_address: true
        # Containers in cab1 need routes to the management network of
        # cab2 and cab3.
        static_routes:
          # Route to cab2
          - cidr: 172.16.2.0/24
            gateway: 172.16.1.1
          # Route to cab3
          - cidr: 172.16.3.0/24
            gateway: 172.16.1.1
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container_cab2"
        type: "raw"
        group_binds:
          - cab2-containers
          - cab2-hosts
        is_container_address: true
        is_ssh_address: true
        # Containers in cab2 need routes to the management network of
        # cab1 and cab3
        static_routes:
          # Route to cab1
          - cidr: 172.16.1.0/24
            gateway: 172.16.2.1
          # Route to cab3
          - cidr: 172.16.3.0/24
            gateway: 172.16.2.1
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container_cab3"
        type: "raw"
        group_binds:
          - cab3-containers
          - cab3-hosts
        is_container_address: true
        is_ssh_address: true
        # Containers in cab3 need routes to the management network of
        # cab1 and cab2
        static_routes:
          # Route to cab1
          - cidr: 172.16.1.0/24
            gateway: 172.16.3.1
          # Route to cab2
          - cidr: 172.16.2.0/24
            gateway: 172.16.3.1
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel_cab1"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - cab1-neutron_linuxbridge_agent
        # Containers in cab1 need routes to the vxlan network of
        # cab2 and cab3.
        static_routes:
          # Route to cab2
          - cidr: 172.17.2.0/24
            gateway: 172.17.1.1
          # Route to cab3
          - cidr: 172.17.3.0/24
            gateway: 172.17.1.1
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel_cab2"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - cab2-neutron_linuxbridge_agent
        # Containers in cab2 need routes to the vxlan network of
        # cab1 and cab3
        static_routes:
          # Route to cab1
          - cidr: 172.17.1.0/24
            gateway: 172.17.2.1
          # Route to cab3
          - cidr: 172.17.3.0/24
            gateway: 172.17.2.1
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel_cab3"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - cab3-neutron_linuxbridge_agent
        # Containers in cab3 need routes to the vxlan network of
        # cab1 and cab2
        static_routes:
          # Route to cab1
          - cidr: 172.17.1.0/24
            gateway: 172.17.3.1
          # Route to cab2
          - cidr: 172.17.2.0/24
            gateway: 172.17.3.1
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "flat"
        range: "1:1"
        net_name: "flat"
        group_binds:
          - cab1-neutron_linuxbridge_agent
          - cab2-neutron_linuxbridge_agent
          - cab3-neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage_cab1"
        type: "raw"
        group_binds:
          - cab1-glance_api
          - cab1-cinder_api
          - cab1-cinder_volume
          - cab1-nova_compute
          - cab1-swift_proxy
        # Containers in cab1 need routes to the storage network of
        # cab2 and cab3
        static_routes:
          # Route to cab2
          - cidr: 172.18.2.0/24
            gateway: 172.18.1.1
          # Route to cab3
          - cidr: 172.18.3.0/24
            gateway: 172.18.1.1
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage_cab2"
        type: "raw"
        group_binds:
          - cab2-glance_api
          - cab2-cinder_api
          - cab2-cinder_volume
          - cab2-nova_compute
          - cab2-swift_proxy
        # Containers in cab2 need routes to the storage network of
        # cab1 and cab3
        static_routes:
          # Route to cab1
          - cidr: 172.18.1.0/24
            gateway: 172.18.2.1
          # Route to cab3
          - cidr: 172.18.3.0/24
            gateway: 172.18.2.1
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage_cab3"
        type: "raw"
        group_binds:
          - cab3-glance_api
          - cab3-cinder_api
          - cab3-cinder_volume
          - cab3-nova_compute
          - cab3-swift_proxy
        # Containers in cab3 need routes to the storage network of
        # cab1 and cab2
        static_routes:
          # Route to cab1
          - cidr: 172.18.1.0/24
            gateway: 172.18.3.1
          # Route to cab2
          - cidr: 172.18.2.0/24
            gateway: 172.18.3.1

cab1-shared-infra_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-shared-infra_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-shared-infra_hosts:
  cab3-infra3:
    ip: 172.16.3.3

cab1-os-infra_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-os-infra_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-os-infra_hosts:
  cab3-infra3:
    ip: 172.16.3.3


cab1-storage-infra_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-storage-infra_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-storage-infra_hosts:
  cab3-infra3:
    ip: 172.16.3.3

cab1-repo-infra_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-repo-infra_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-repo-infra_hosts:
  cab3-infra3:
    ip: 172.16.3.3

cab1-identity_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-identity_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-identity_hosts:
  cab3-infra3:
    ip: 172.16.3.3

cab1-compute_hosts:
  cab1-compute1:
    ip: 172.16.1.4
cab2-compute_hosts:
  cab2-compute2:
    ip: 172.16.2.6

cab3-storage_hosts:
  cab3-storage1:
    ip: 172.16.3.5
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI

cab1-log_hosts:
  cab1-compute1:
    ip: 172.16.1.4

cab1-network_hosts:
  cab1-infra1:
    ip: 172.16.1.3
cab2-network_hosts:
  cab2-infra2:
    ip: 172.16.2.3
cab3-network_hosts:
  cab3-infra3:
    ip: 172.16.3.3

haproxy_hosts:
  walmart-router:
    ip: 172.16.1.1
